"""initial schema

Revision ID: 75cd02f1b576
Revises: 
Create Date: 2026-03-19 15:26:57.083085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75cd02f1b576'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_year', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.String(length=10), nullable=False),
    sa.Column('chamber', sa.String(length=10), nullable=False),
    sa.Column('bill_number_numeric', sa.Integer(), nullable=False),
    sa.Column('current_title', sa.Text(), nullable=False),
    sa.Column('committee_name', sa.String(length=200), nullable=True),
    sa.Column('bill_status_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_year', 'bill_id', name='uq_bill_session_year_bill_id')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('alert_threshold', sa.Integer(), nullable=False),
    sa.Column('digest_threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('source_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('session_year', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('raw_html_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_interest_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id_fk', sa.Integer(), nullable=False),
    sa.Column('profile_yaml', sa.Text(), nullable=False),
    sa.Column('profile_text_for_embedding', sa.Text(), nullable=True),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id_fk'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_copies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id_fk', sa.Integer(), nullable=False),
    sa.Column('session_year', sa.Integer(), nullable=False),
    sa.Column('file_copy_number', sa.Integer(), nullable=False),
    sa.Column('canonical_version_id', sa.String(length=30), nullable=False),
    sa.Column('listing_date', sa.String(length=10), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=False),
    sa.Column('pdf_sha256', sa.String(length=64), nullable=True),
    sa.Column('local_pdf_path', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id_fk'], ['bills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_version_id'),
    sa.UniqueConstraint('canonical_version_id', name='uq_file_copy_canonical_version_id')
    )
    op.create_index('ix_file_copy_bill_id', 'file_copies', ['bill_id_fk'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id_fk', sa.Integer(), nullable=False),
    sa.Column('bill_id_fk', sa.Integer(), nullable=False),
    sa.Column('canonical_version_id', sa.String(length=30), nullable=False),
    sa.Column('urgency', sa.String(length=10), nullable=False),
    sa.Column('alert_disposition', sa.String(length=30), nullable=False),
    sa.Column('alert_text', sa.Text(), nullable=False),
    sa.Column('telegram_message_id', sa.String(length=50), nullable=True),
    sa.Column('suppression_key', sa.String(length=200), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id_fk'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['canonical_version_id'], ['file_copies.canonical_version_id'], ),
    sa.ForeignKeyConstraint(['client_id_fk'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_diffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id_fk', sa.Integer(), nullable=False),
    sa.Column('current_version_id', sa.String(length=30), nullable=False),
    sa.Column('prior_version_id', sa.String(length=30), nullable=True),
    sa.Column('compared_against', sa.String(length=20), nullable=False),
    sa.Column('sections_added', sa.Integer(), nullable=False),
    sa.Column('sections_removed', sa.Integer(), nullable=False),
    sa.Column('sections_modified', sa.Integer(), nullable=False),
    sa.Column('effective_date_old', sa.String(length=100), nullable=True),
    sa.Column('effective_date_new', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id_fk'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['current_version_id'], ['file_copies.canonical_version_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_version_id', sa.String(length=30), nullable=False),
    sa.Column('section_id', sa.String(length=50), nullable=False),
    sa.Column('heading', sa.Text(), nullable=False),
    sa.Column('start_page', sa.Integer(), nullable=False),
    sa.Column('end_page', sa.Integer(), nullable=False),
    sa.Column('start_char', sa.Integer(), nullable=False),
    sa.Column('end_char', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_version_id'], ['file_copies.canonical_version_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_text_extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_version_id', sa.String(length=30), nullable=False),
    sa.Column('full_raw_text', sa.Text(), nullable=False),
    sa.Column('full_cleaned_text', sa.Text(), nullable=False),
    sa.Column('overall_extraction_confidence', sa.Float(), nullable=False),
    sa.Column('extraction_warnings_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_version_id'], ['file_copies.canonical_version_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_bill_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id_fk', sa.Integer(), nullable=False),
    sa.Column('bill_id_fk', sa.Integer(), nullable=False),
    sa.Column('canonical_version_id', sa.String(length=30), nullable=False),
    sa.Column('rules_score', sa.Float(), nullable=False),
    sa.Column('embedding_score', sa.Float(), nullable=False),
    sa.Column('llm_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('urgency', sa.String(length=10), nullable=False),
    sa.Column('should_alert', sa.Boolean(), nullable=False),
    sa.Column('alert_disposition', sa.String(length=30), nullable=False),
    sa.Column('reasons_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id_fk'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['canonical_version_id'], ['file_copies.canonical_version_id'], ),
    sa.ForeignKeyConstraint(['client_id_fk'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id_fk', sa.Integer(), nullable=False),
    sa.Column('bill_id_fk', sa.Integer(), nullable=False),
    sa.Column('canonical_version_id', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id_fk'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['canonical_version_id'], ['file_copies.canonical_version_id'], ),
    sa.ForeignKeyConstraint(['client_id_fk'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_change_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_diff_id', sa.Integer(), nullable=False),
    sa.Column('change_flag', sa.String(length=50), nullable=False),
    sa.Column('section_id', sa.String(length=50), nullable=True),
    sa.Column('old_text_summary', sa.Text(), nullable=False),
    sa.Column('new_text_summary', sa.Text(), nullable=False),
    sa.Column('practical_effect', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bill_diff_id'], ['bill_diffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_text_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('cleaned_text', sa.Text(), nullable=False),
    sa.Column('extraction_method', sa.String(length=10), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['bill_text_extractions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_text_pages')
    op.drop_table('bill_change_events')
    op.drop_table('feedback_labels')
    op.drop_table('client_bill_scores')
    op.drop_table('bill_text_extractions')
    op.drop_table('bill_sections')
    op.drop_table('bill_diffs')
    op.drop_table('alerts')
    op.drop_index('ix_file_copy_bill_id', table_name='file_copies')
    op.drop_table('file_copies')
    op.drop_table('client_interest_profiles')
    op.drop_table('source_pages')
    op.drop_table('clients')
    op.drop_table('bills')
    # ### end Alembic commands ###
